{% set name = "zeep" %}
{% set version = "2.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4f9db52c7d269813fc6251da4cb050869158858aeea75a055b4550f19e52ac84

build:
  number: 2000
  script: "{{ PYTHON }} -m pip install . -vv"
  preserve_egg_dir: True

requirements:
  host:
    - appdirs >=1.4.0
    - cached-property >=1.3.0
    - defusedxml >=0.4.1
    - isodate >=0.5.4
    - lxml >=3.0.0
    - pip
    - python ==2.7.18
    - pytz
    - requests >=2.7.0
    - requests-toolbelt >=0.7.1
    - six >=1.9.0
  run:
    - appdirs >=1.4.0
    - cached-property >=1.3.0
    - defusedxml >=0.4.1
    - isodate >=0.5.4
    - lxml >=3.0.0
    - python
    - pytz
    - requests >=2.7.0
    - requests-toolbelt >=0.7.1
    - six >=1.9.0

#test:
#  imports:
#    - zeep
#  requires:
#    - aioresponses >=0.1.3
#    - flake8 ==3.3.0
#    - flake8-blind-except ==0.1.1
#    - flake8-debugger ==1.4.0
#    - flake8-imports ==0.1.1
#    - freezegun ==0.3.8
#    - isort ==4.2.15
#    - mock ==2.0.0
#    - pretend ==1.0.8
#    - pytest ==3.1.3
#    - pytest-cov ==2.5.1
#    - pytest-tornado ==0.4.5
#    - requests_mock >=0.7.0

about:
  home: "http://docs.python-zeep.org"
  license: MIT
  license_family: MIT
  license_file:
  summary: "A modern/fast Python SOAP client based on lxml / requests"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - pythoext
