{% set name = "infix" %}
{% set version = "1.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a1bfdcf875bc072f41e426d0673f2e3017750743bb90cc725fffb292eb09648c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  preserve_egg_dir: True

requirements:
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/borntyping/python-infix
  license: MIT
  license_family: MIT
  license_file: ''
  summary: Infix operators for Python
  description: "=====\nInfix\n=====\n\n.. image:: http://img.shields.io/pypi/v/infix.svg\n    :target: https://pypi.python.org/pypi/infix/\n    :alt: Latest PyPI version\n\n.. image:: https://travis-ci.org/borntyping/python-infix.svg\n\
    \    :target: https://travis-ci.org/borntyping/python-infix\n    :alt: Travis build status\n\nA decorator that allows functions to be used as infix functions.\n\nInfix operators are created and applied\
    \ as such, and do not stop the function from being called normally::\n\n    >>> from infix import shift_infix as infix\n    ... \n    >>> @infix\n    ... def plus(a, b):\n    ...     return a + b\n\
    \    ...\n    >>> print(40 <<plus>> 2)\n    42\n    >>> print(plus(5, 5))\n    10\n\nVariant syntaxes\n----------------\n\nMultiple infix syntaxes are provided by the ``infix`` module::\n\n    >>> @and_infix\n\
    \    ... def is_before(a, b):\n    ...     return a < b\n    ...\n    >>> print(1 &is_before& 5)\n    True\n\n    >>> @or_infix\n    ... def minus(a, b):\n    ...     return a - b\n    ...\n    >>>\
    \ print(1 |minus| 2)\n    -1\n\n    >>> @xor_infix\n    ... def until(start, stop):\n    ...     return range(start, stop)\n    ...\n    >>> print(list(1 ^until^ 10))\n    [1, 2, 3, 4, 5, 6, 7, 8, 9]\n\
    \n    >>> @pow_infix\n    ... def pow(a, b):\n    ...     return a**b\n    ...\n    >>> print(3 **pow** 2)\n    9\n    \n    >>> dpow = div_infix(pow)\n    >>> print(3 /dpow/ 2)\n    9\n\nCustom syntaxes\n\
    ----------------\n\nPython has a large set of operators than could be overridden to provide the infix syntax, so instead of providing them all a ``make_infix`` function is provided. To use it, pass\
    \ the names of the operatorsyou want to support::\n\n    >>> @make_infix('mod','pow','rshift')\n    ... def until(start, stop):\n    ...     return list(range(start, stop))\n    >>> print(1 %until%\
    \ 3)\n    [1, 2]\n    >>> print(2 <<until>> 4)\n    [2, 3]\n    >>> print(5 **until** 8)\n    [5, 6, 7]\n    >>> print(until(10,12))\n    [10, 11]\n\n.. versionadded:: 1.2\n\nThe old ``custom_infix``\
    \ is still supported. It takes two parameters, the names of the left and right operator functions, though only the first is important::\n\n    >>> @custom_infix('__rmod__', '__mod__')\n    ... def ate(a,\
    \ b):\n    ...     return (a == 7 and b == 9)\n    ...\n    >>> print(7 %ate% 9)\n    True\n    >>> print(6 %ate% 7)\n    False\n\nThe left function should be a `right operand <http://docs.python.org/2/reference/datamodel.html#object.__radd__>`_,\
    \ and the right functions should be a `left operand <http://docs.python.org/2/reference/datamodel.html#object.__add__>`_.\n\nYou should be careful to avoid using operands that the objects your functions\
    \ will take may provide themselves (as the initial right operand is only called if the previous object does not provide for that operand).\n\nBinding\n-------\n\nThe library now uses a binding feature\
    \ to generate a temporary object halfway through the process. That means that half expressions now work::\n\n    >>> 3**pow\n    <pow_lbind: Waiting for right side>\n\n\n.. versionadded:: 1.2\n\nExample:\
    \ Currying\n-----------------\n\nOne possible use is in curring functions in Python. You can easily define a\ncurry function::\n\n    >>> from functools import partial\n    >>> curry = or_infix(partial)\n\
    \    >>> def volume(x, y, z):\n    ...    return x * y * z\n    >>> tot = volume |curry| 2 |curry| 3 |curry| 4\n    >>> tot()\n    24\n\nCompatibility\n-------------\n\nWorks on all major Python versions\
    \ (2.6, 2.7, 3.2, 3.3, 3.4).\n\nTests\n-----\n\nThe tests in this README files are run using `doctest`_. To run the tests, run ''python infix.py'' - alternatively, use `tox`_ to run the tests on all\
    \ compatible Python versions.\n\n.. _doctest: http://docs.python.org/3/library/doctest.html\n.. _tox: http://testrun.org/tox/\n\nLicence\n-------\n\nCopyright (C) 2013 Sam Clements\n\nPermission is\
    \ hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without\
    \ limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to\
    \ the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT\
    \ WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\
    \ HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS\
    \ IN THE SOFTWARE.\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
