{% set name = "mongoengine" %}
{% set version = "0.10.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1db3a8b0f2ccc47dbeef5fb028c600143531203d1cd3c1099483829be09b8e79

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  preserve_egg_dir: True


requirements:
  host:
    - pip
    - pymongo >=2.7.1
    - python ==2.7.18
    - six
  run:
    - pymongo >=2.7.1
    - python
    - six

test:
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset
  requires:
    - blinker
    #- coverage ==3.7.1
    #- nose
    - pillow >=2.0.0

about:
  home: "http://mongoengine.org/"
  license: MIT
  license_family: MIT
  license_file:
  summary: "MongoEngine is a Python Object-Document Mapper for working with MongoDB."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - pythoext
